# This is a simon configuration file :)
# It tells what container to attach to what tmux setup (and more...)

entities: # Each entity assumes service and container name are the same in docker compose !
  gazebo_sitl:
    compose: docker-compose.yml
    entry_points:
      - command: bash
        run_in_window: container_terminal
      - command: ros2 topic echo /odometry
        run_in_window: odometry
      - command: ros2 launch mavros apm.launch fcu_url:=udp://127.0.0.1:5761@ gcs_url:=udp://@
        run_in_window: mavros
      - command: ros2 topic echo /mavros/local_position/pose
        run_in_window: mavros_pose
    interactive: true
    gpu: true

  mission_planner:
    compose: docker-compose.yml
    interactive: true

  qgc:
    compose: docker-compose.yml
    interactive: true

default_group: nablus  # default group to run when using: simon up

groups:
  nablus: 
    description: Simulation for iris drone using sitl + gazebo + mavros on nablus omniverse map
    entities:
      - gazebo_sitl
#      - mission_planner
      - qgc

  telem:
    description: Simulation for iris drone using sitl + gazebo + mavros on telem omniverse map
    compose_override: docker_compose_override/docker-compose.telem.yml
    entities:
      - gazebo_sitl
      - mission_planner