# This is a simon configuration file :)
# It tells what container to attach to what tmux setup (and more...)

entities: # Each entity assumes service and container name are the same in docker compose !
  gazebo_sitl:
    compose: docker-compose.yml
    entry_points:
      - command: bash
        run_in_window: container_terminal
      - command: gz gazebo -v4 -r iris_runway.sdf
        run_in_window: gazebo
      - command: python3 /home/ros2/humble_ws/src/ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter -f gazebo-iris --model JSON --map --console
        run_in_window: sitl
      - command: ros2 launch mavros apm.launch fcu_url:=tcp://localhost gcs_url:=udp://@
        run_in_window: mavros
      - command: ros2 topic echo /mavros/local_position/pose
        run_in_window: /mavros/local_position/pose
    interactive: false
    gpu: true

  mission_planner:
    compose: docker-compose.yml
    interactive: true

default_group: full_sim  # default group to run when using: simon up

groups:
  full_sim:
    description: Simulation for iris drone using sitl + gazebo + mavros.
    run_local: false  # run in network_mode: host
    entities:
      - gazebo_sitl
      - mission_planner
