# This is a simon configuration file :)
# It tells what container to attach to what tmux setup (and more...)

entities: # Each entity assumes service and container name are the same in docker compose !
  gazebo_sitl:
    compose: docker-compose.yml
    entry_points:
      - command: bash
        run_in_window: container_terminal
      - command: ros2 topic echo /odometry
        run_in_window: odometry
      - command: ros2 launch mavros apm.launch fcu_url:=udp://127.0.0.1:5761@ gcs_url:=udp://@
        run_in_window: mavros
      - command: ros2 topic echo /mavros/local_position/pose
        run_in_window: mavros_pose
    interactive: false
    gpu: true

  mission_planner:
    compose: docker-compose.yml
    interactive: false

default_group: nablus  # default group to run when using: simon up

groups:
  nablus: 
    description: Simulation for iris drone using sitl + gazebo + mavros on nablus omniverse map
    entities:
      - gazebo_sitl
      - mission_planner
    group_entry_points:
      gazebo_sitl:
        - command: ros2 launch ardupilot_gz_bringup iris_maze.launch.py out:=udp:127.0.0.1:5761 home:="32.22481,35.25621,499.02000, 0" console:=True
          run_in_window: "gazebo"
  telem: 
    description: Simulation for iris drone using sitl + gazebo + mavros on telem omniverse map
    entities:
      - gazebo_sitl
      - mission_planner
    group_entry_points:
      gazebo_sitl:
        - command: ros2 launch ardupilot_gz_bringup iris_maze.launch.py out:=udp:127.0.0.1:5761 home:="33.253,35.52472,582.54, 0" console:=True
          run_in_window: "gazebo"