version: '3.3'

services:
#   mission_planner:
#     build:
#       context: .
#       dockerfile: mission_planner.dockerfile
#     image: mission_planner:1.0.0
#     container_name: mission_planner
#     network_mode: host
#     environment:
#       - DISPLAY=$DISPLAY
#     volumes:
#       - /tmp/.X11-unix:/tmp/.X11-unix:rw
#     tty: true
#     stdin_open: true
#     privileged: true

  gazebo-sitl:
    build:
      context: .
      dockerfile: gazebo_sitl.dockerfile
    image: gazebo_sitl:humble_garden
    command: bash
    container_name: gazebo-sitl
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./humble_ws/src:/home/ros2/humble2_
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    ipc: host
    pid: host
    runtime: nvidia
    tty: true
    stdin_open: true
    privileged: true

  sitl:
    build:
      context: .
      dockerfile: sitl.dockerfile
    image: sitl:Copter-4.0.5
    container_name: sitl
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    privileged: true
    tty: true
