version: '3.3'

services:
  mission_planner:
    build:
      context: .
      dockerfile: mission_planner.dockerfile
    image: mission_planner:1.0.0
    container_name: mission_planner
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true
    privileged: true

  gazebo_sitl:
    build:
      context: .
      dockerfile: gazebo_sitl.dockerfile
    image: gazebo_sitl:humble_garden
    command: bash
    container_name: gazebo_sitl
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true
    privileged: true
