version: '3.3'

services:
  mission_planner:
    build:
      context: .
      dockerfile: mission_planner.dockerfile
    image: mission_planner:1.3.75
    container_name: mission_planner
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true
    privileged: true

  gazebo_sitl:
    build:
      context: .
      dockerfile: gazebo_sitl.dockerfile
    image: gazebo_sitl:humble_garden
    container_name: gazebo_sitl
    command: bash -ic 'ros2 launch ardupilot_gz_bringup iris_maze.launch.py out:=udp:127.0.0.1:5761 home:="32.22481,35.25621,499.02000,0" console:=True'
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true
    privileged: true
